### ISSUE TITLE
Setting uniqueVersion to false causes Ivy deployment errors

### ISSUE THREAD

**Issue by shevek** [bmuschko/gradle-nexus-plugin#35]
This one is a puzzle:

```
uploadArchives{
    repositories {
        mavenDeployer()
    }
}
```

causes

```
Caused by: A distributionManagement element or remoteRepository element is required to deploy
        at org.apache.maven.artifact.ant.DeployTask.getDeploymentRepository(DeployTask.java:186)
        at org.apache.maven.artifact.ant.DeployTask.doExecute(DeployTask.java:115)
        at org.gradle.api.publication.maven.internal.ant.CustomDeployTask.doExecute(CustomDeployTask.java:39)
        at org.apache.maven.artifact.ant.AbstractArtifactTask.execute(AbstractArtifactTask.java:751)
        at org.gradle.api.publication.maven.internal.ant.AbstractMavenResolver.execute(AbstractMavenResolver.java:111)
        at org.gradle.api.publication.maven.internal.ant.AbstractMavenResolver.publish(AbstractMavenResolver.java:102)
        at org.gradle.api.publication.maven.internal.ant.AbstractMavenResolver.publish(AbstractMavenResolver.java:80)
        at org.gradle.api.internal.artifacts.ivyservice.DefaultIvyDependencyPublisher.publish(DefaultIvyDependencyPublisher.java:42)
        at org.gradle.api.internal.artifacts.ivyservice.IvyBackedArtifactPublisher$1.execute(IvyBackedArtifactPublisher.java:79)
        at org.gradle.api.internal.artifacts.ivyservice.IvyBackedArtifactPublisher$1.execute(IvyBackedArtifactPublisher.java:54)
        at org.gradle.internal.Transformers$3.transform(Transformers.java:131)
        at org.gradle.api.internal.artifacts.ivyservice.DefaultIvyContextManager.withIvy(DefaultIvyContextManager.java:61)
        at org.gradle.api.internal.artifacts.ivyservice.DefaultIvyContextManager.withIvy(DefaultIvyContextManager.java:39)
        at org.gradle.api.internal.artifacts.ivyservice.IvyBackedArtifactPublisher.publish(IvyBackedArtifactPublisher.java:54)
        at org.gradle.api.tasks.Upload.upload(Upload.java:64)
        ... 77 more
```

Now what I want to do is `mavenDeployer { uniqueVersion = false }` because I don't want datestamps in snapshots.

Can this be done in gradle-nexus-plugin?

**Comment by bmuschko** [comment]
This plugin reached EOL and will add no more new features.
